version: '3'

services:
  django:
    restart: always
    build:
      context: .
      dockerfile: compose/Dockerfile
    restart: always
    volumes:
      - ./:/app
    ports:
      - "8001:8001"
    entrypoint: compose/entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres
    restart: always