# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-07 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
